### ISSUE TITLE
XRSceneAnchorComponents -- Static Mesh Collision Response Channels not working

### ISSUE THREAD

**Issue by brycelynch** [oculus-samples/Unreal-Scene#4]
Doesn't appear that collision response channels work on static meshes that are being referenced in SceneAnchorComponent.   If collision is complete removed there is no collision... but custom setup to ignore specific traces appear to be getting ignored.

**Comment by connorhollis-meta** [comment]
The AOculusXRSceneActor type and associated classes are now deprecated, including UOculusXRSceneAnchorComponent.

We recommend using MRUK instead. There is a migration doc [here](https://developers.meta.com/horizon/documentation/unreal/unreal-scene-migrate-mruk/). And we also have [generalized documentation](https://developers.meta.com/horizon/documentation/unreal/unreal-mr-utility-kit-overview) available.
