### ISSUE TITLE
Access XRSceneActor's Point data?

### ISSUE THREAD

**Issue by HeberRyan** [oculus-samples/Unreal-Scene#6]
Currently, I'm trying to make a real-world 'passthrough window' by getting spatial data through OculusXRSceneActor and Oculus XRPassthrough Layer Component(UserDefined Overlay), but I can not get the scene point only static mesh from XRSceneActor, Does it available to get the point data from the XRSceneActor or the spatial anchor? Any help will be appreciated!

**Comment by HeberRyan** [comment]
I wanna use the dynamic mesh for the wall and the passthrough window so that the user can adjust the window location by the way.

**Comment by dinversinimeta** [comment]
Hi @HeberRyan 

Thank you for raising this question. 
If I understand you correctly (cut a hole in the wall to see the real window), I'd like to forward you to MRUK: https://github.com/oculus-samples/Unreal-MRUtilityKitSample 

MRUK (Mixed Reality Utility Kit) is the advanced Scene integration which has such features built already inside. Look for "GenerateProceduralAnchorMesh" with the parameter "CutHoles".

Let us know if we did not understand your request correctly.

Daniel

**Comment by HeberRyan** [comment]
Thank you, Daniel. I really appreciate your support! I'll give it a try later :)

Best
Ryan
